# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cd839425f588f3af5fc7e0160681c17f8e7d044d5333d91ba5578980077a80abd261d425aba038ea97c8091ea5583afe02139210b062acc5d4a050da65e75c4

test:
  secret_key_base: 575e0e0e3eb8112dad06901b066208a40d4450f1346bab3e12f3d8fa9d6d859ca6e12579b7d4e68347db79738c4d29699a9169ec7859d789005b16ea0f9b3aae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
